#!/usr/bin/env bash
set -euo pipefail

task_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
task_project_dir="$(cd -- "${task_script_dir}/.." && pwd)"
task_failures=0

require_pattern() {
  local task_file="$1"
  local task_pattern="$2"
  local task_description="$3"
  if rg -q -- "${task_pattern}" "${task_project_dir}/${task_file}"; then
    printf 'PASS  %s\n' "${task_description}"
  else
    printf 'FAIL  %s (%s)\n' "${task_description}" "${task_file}" >&2
    task_failures=$((task_failures + 1))
  fi
}

reject_pattern() {
  local task_file="$1"
  local task_pattern="$2"
  local task_description="$3"
  if rg -q -- "${task_pattern}" "${task_project_dir}/${task_file}"; then
    printf 'FAIL  %s (%s)\n' "${task_description}" "${task_file}" >&2
    task_failures=$((task_failures + 1))
  else
    printf 'PASS  %s\n' "${task_description}"
  fi
}

require_file() {
  local task_file="$1"
  local task_description="$2"
  if [[ -f "${task_project_dir}/${task_file}" ]]; then
    printf 'PASS  %s\n' "${task_description}"
  else
    printf 'FAIL  %s (%s)\n' "${task_description}" "${task_file}" >&2
    task_failures=$((task_failures + 1))
  fi
}

require_pattern_order() {
  local task_file="$1"
  local task_first_pattern="$2"
  local task_second_pattern="$3"
  local task_description="$4"
  local task_first_match
  local task_second_match
  local task_first_line
  local task_second_line

  task_first_match="$(rg -n -m 1 -- "${task_first_pattern}" \
    "${task_project_dir}/${task_file}" || true)"
  task_second_match="$(rg -n -m 1 -- "${task_second_pattern}" \
    "${task_project_dir}/${task_file}" || true)"
  task_first_line="${task_first_match%%:*}"
  task_second_line="${task_second_match%%:*}"
  if [[ "${task_first_line}" =~ ^[0-9]+$ && \
        "${task_second_line}" =~ ^[0-9]+$ ]] && \
      ((task_first_line < task_second_line)); then
    printf 'PASS  %s\n' "${task_description}"
  else
    printf 'FAIL  %s (%s)\n' "${task_description}" "${task_file}" >&2
    task_failures=$((task_failures + 1))
  fi
}

reject_file() {
  local task_file="$1"
  local task_description="$2"
  if [[ -e "${task_project_dir}/${task_file}" ]]; then
    printf 'FAIL  %s (%s)\n' "${task_description}" "${task_file}" >&2
    task_failures=$((task_failures + 1))
  else
    printf 'PASS  %s\n' "${task_description}"
  fi
}

require_pattern ECU.ioc '^PB2.GPIO_Label=ESTOP_DETECT$' 'E-stop is mapped to schematic pin PB2'
reject_pattern ECU.ioc '(^|,)(PG2|LPUART1|NUCLEO-H563ZI)(\\:I)?(,|$)|^BSP_IP_NAME=' 'No Nucleo/LPUART/PG2 ghost configuration remains'
require_pattern ECU.ioc '^board=custom$' 'CubeMX project targets the custom ECU board'
require_pattern ECU.ioc '^ProjectManager.KeepUserCode=true$' 'CubeMX user-code preservation is enabled'
require_pattern ECU.ioc '^PB8.GPIO_Label=SW_I2C_SDA$' 'PCB R1 swapped PB8 is persistently assigned software SDA'
require_pattern ECU.ioc '^PB9.GPIO_Label=SW_I2C_SCL$' 'PCB R1 swapped PB9 is persistently assigned software SCL'
require_pattern ECU.ioc '^PB8.GPIO_ModeDefaultOutputPP=GPIO_MODE_OUTPUT_OD$' 'PB8 software I2C is open-drain in CubeMX'
require_pattern ECU.ioc '^PB9.GPIO_ModeDefaultOutputPP=GPIO_MODE_OUTPUT_OD$' 'PB9 software I2C is open-drain in CubeMX'
reject_pattern ECU.ioc '^(PB8|PB9)[.]Signal=I2C1_' 'Hardware I2C alternate functions are not used on PCB R1'
reject_file Secure/Core/Src/i2c.c 'Obsolete generated hardware I2C implementation is absent'
require_pattern ECU.ioc '^GTZC_S.ADC_Secure=GTZC_TZSC_PERIPH_SEC$' 'ADC1/ADC2 are Secure'
require_pattern ECU.ioc '^GTZC_S.TIM4_Secure=GTZC_TZSC_PERIPH_SEC$' 'Valve PWM timer is Secure'
require_pattern ECU.ioc '^GTZC_S.TIM7_Secure=GTZC_TZSC_PERIPH_SEC$' 'Independent microsecond timer is Secure'
require_pattern ECU.ioc '^GTZC_S.IWDG_Secure=GTZC_TZSC_PERIPH_SEC$' 'IWDG is Secure'
require_pattern ECU.ioc '^GTZC_S.SPI4_Secure=GTZC_TZSC_PERIPH_SEC$' 'TPIC SPI4 is Secure'
require_pattern ECU.ioc '^GPDMA1.ChannelPRIV_GPDMACH0=DMA_CHANNEL_PRIV$' 'ADC1 DMA channel is privileged for Secure SRAM access'
require_pattern ECU.ioc '^GPDMA1.ChannelPRIV_GPDMACH1=DMA_CHANNEL_PRIV$' 'ADC2 DMA channel is privileged for Secure SRAM access'
require_pattern ECU.ioc '^ADC1.ExternalTrigConv=ADC_EXTERNALTRIG_T6_TRGO$' 'Slow ADC scan is hardware-triggered at 1 kHz'
require_pattern ECU.ioc '^ADC2.ExternalTrigConv=ADC_EXTERNALTRIG_T4_TRGO$' 'Current ADC scan is synchronized to PWM'
require_pattern ECU.ioc '^ADC2[.]SamplingTime-0.*=ADC_SAMPLETIME_12CYCLES_5$' 'Forward-current ADC sampling time supports the 20 kHz loop'
require_pattern ECU.ioc '^ADC2[.]SamplingTime-1.*=ADC_SAMPLETIME_12CYCLES_5$' 'Reverse-current ADC sampling time supports the 20 kHz loop'
require_pattern ECU.ioc '^ADC1[.]SamplingTime-7.*ChannelRegularConversion=ADC_SAMPLETIME_640CYCLES_5$' 'VREFINT sampling time satisfies the datasheet minimum'
require_pattern ECU.ioc '^TIM4[.]Channel-PWM.*Generation4.*No.*Output=TIM_CHANNEL_4$' 'Internal TIM4 CH4 midpoint trigger is persistent'
require_pattern ECU.ioc '^TIM4.CounterMode=TIM_COUNTERMODE_CENTERALIGNED1$' 'Valve PWM is center aligned'
require_pattern ECU.ioc '^TIM4.PulseNoDither_4=1$' 'ADC2 trigger is at the center-aligned PWM conduction valley'
require_pattern ECU.ioc '^TIM7.Prescaler=249$' 'Secure microsecond timer runs from the reviewed 250 MHz timer clock'
require_pattern ECU.ioc '^TIM7.PeriodNoDither=65535$' 'Secure microsecond timer uses the full 16-bit free-running period'
require_pattern ECU.ioc '^NVIC1.ADC2_IRQn=true\\:1\\:0' 'ADC2 control-loop IRQ priority is persisted as 1'
require_pattern ECU.ioc '^NVIC1.GPDMA1_Channel1_IRQn=true\\:1\\:0' 'ADC2 DMA IRQ priority is persisted as 1'
require_pattern ECU.ioc '^FDCAN1.CalculateBaudRateNominal=250000$' 'FDCAN1 nominal bitrate is 250 kbit/s'
require_pattern ECU.ioc '^FDCAN2.CalculateBaudRateNominal=250000$' 'FDCAN2 nominal bitrate is 250 kbit/s'
require_pattern ECU.ioc '^FDCAN1.ExtFiltersNbr=6$' 'CAN1 reserves exactly six J1939 extended filters'
require_pattern ECU.ioc '^FDCAN1.StdFiltersNbr=0$' 'CAN1 has no unspecified standard-ID filters'
require_pattern ECU.ioc '^FDCAN2.ExtFiltersNbr=0$' 'CAN2 remains reserved and unstarted'
require_pattern ECU.ioc '^SPI4.DataSize=SPI_DATASIZE_8BIT$' 'TPIC SPI words are 8 bit'
require_pattern ECU.ioc '^SPI4.BaudRatePrescaler=SPI_BAUDRATEPRESCALER_32$' 'TPIC SPI clock is derated to 3.90625 Mbit/s'
require_pattern ECU.ioc '^ETH.MACAddr=8A\\:EA\\:B5\\:00\\:00\\:02$' 'Legacy ECU MAC address is persisted in CubeMX'
require_pattern ECU.ioc '^TIM2.ICFilter_CH1=8$' 'Speed capture input filter is persisted'
require_pattern ECU.ioc '^IWDG.Reload=1999$' 'Secure watchdog timeout baseline is persisted'
require_pattern ECU.ioc '^RCC.EnbaleCSS=true$' 'HSE clock security system is enabled'
require_pattern Secure/Core/Src/tim.c 'sConfigOC.Pulse = 1;' 'Generated TIM4 ADC trigger compare is present'
require_pattern Secure/Core/Src/adc.c 'HAL_NVIC_SetPriority[(]ADC2_IRQn, 1, 0[)]' 'Generated ADC2 IRQ priority is 1'
require_pattern Secure/Core/Src/gpdma.c 'HAL_NVIC_SetPriority[(]GPDMA1_Channel1_IRQn, 1, 0[)]' 'Generated ADC2 DMA IRQ priority is 1'
require_pattern Secure/Core/Src/gpio.c 'GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_OD;' 'Generated software I2C pins remain open-drain'
require_pattern Secure/Core/Src/gpio.c 'TPIC_OE_N_Pin, GPIO_PIN_SET' 'Generated TPIC output-enable boot level is fail-safe'
require_pattern Secure/Core/Src/gtzc_s.c 'GTZC_PERIPH_ADC12, GTZC_TZSC_PERIPH_SEC' 'Generated GTZC code secures ADC12'
require_pattern Secure/Core/Src/gtzc_s.c 'GTZC_PERIPH_SPI4, GTZC_TZSC_PERIPH_SEC' 'Generated GTZC code secures SPI4'
require_pattern Secure/Core/Src/gtzc_s.c 'GTZC_PERIPH_TIM7, GTZC_TZSC_PERIPH_SEC' 'Generated GTZC code secures the independent microsecond timer'
require_pattern Secure/Core/Src/adc.c 'handle_GPDMA1_Channel0, DMA_CHANNEL_PRIV[|]DMA_CHANNEL_SEC' 'Generated ADC1 DMA is Secure and privileged'
require_pattern Secure/Core/Src/adc.c 'handle_GPDMA1_Channel1, DMA_CHANNEL_PRIV[|]DMA_CHANNEL_SEC' 'Generated ADC2 DMA is Secure and privileged'
require_pattern Secure/Core/Src/gtzc_s.c '^#define ETH_DMA_SRAM3_PRIV_VECTOR_COUNT[[:space:]]+4U' 'ETH DMA non-privileged SRAM3 exception is bounded to 64 KiB'
require_pattern Secure/Core/Src/gtzc_s.c 'HAL_GTZC_MPCBB_GetConfigMem[(]SRAM3_BASE, &ethernet_dma_area_desc[)]' 'ETH DMA SRAM3 exception preserves generated GTZC attributes'
require_pattern Secure/Core/Src/gtzc_s.c 'MPCBB_PrivConfig_array\[ethernet_dma_vector\] = 0U;' 'ETH DMA SRAM3 vectors are made non-privileged in preserved USER CODE'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_CTRL_ENABLE[[:space:]]+0' 'Secure application keeps the ST OEMiROT disabled-SAU model'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_CTRL_ALLNS[[:space:]]+1' 'Disabled SAU delegates final attribution to the STM32H5 IDAU'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION0[[:space:]]+0' 'SAU region 0 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION1[[:space:]]+0' 'SAU region 1 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION2[[:space:]]+0' 'SAU region 2 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION3[[:space:]]+0' 'SAU region 3 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION4[[:space:]]+0' 'SAU region 4 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION5[[:space:]]+0' 'SAU region 5 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION6[[:space:]]+0' 'SAU region 6 is disabled'
require_pattern Secure/Core/Inc/partition_stm32h563xx.h '^#define SAU_INIT_REGION7[[:space:]]+0' 'SAU region 7 is disabled'
reject_pattern Secure/Core/Src/main.c 'SAU->' 'Secure main cannot reactivate inherited RSS/DA SAU comparators'
require_pattern Secure/App/Src/software_i2c.c 'pulse < 9U' 'Software I2C includes bounded nine-clock bus recovery'
require_pattern Secure/App/Src/software_i2c.c '^bool SoftwareI2C_Synchronize[(]void[)]$' 'ATECC host-reset recovery has a dedicated I2C synchronization primitive'
require_pattern Secure/App/Src/software_i2c.c 'clock nine complete bits with SDA held high' 'ATECC synchronization unconditionally clocks nine released-SDA bits'
require_pattern Secure/App/Src/software_i2c.c '!SoftwareI2C_Start[(][)] [|][|] !SoftwareI2C_Stop[(][)]' 'ATECC synchronization terminates the nine-clock sequence with START/STOP'
require_pattern Secure/App/Src/software_i2c.c 'SecureTimebase_HasElapsed' 'Software I2C timing is independent of the debug domain'
require_pattern Secure/App/Src/safety_service.c 'SecureTimebase_DelayUs' 'TPIC timing is independent of the debug domain'
reject_pattern Secure/App/Src/software_i2c.c '(DWT->|CoreDebug->|DWT_|CoreDebug_)' 'Software I2C has no DWT/CoreDebug dependency'
reject_pattern Secure/App/Src/safety_service.c '(DWT->|CoreDebug->|DWT_|CoreDebug_)' 'Secure safety service has no DWT/CoreDebug dependency'
require_file Secure/App/Src/secure_timebase.c 'Secure TIM7 microsecond timebase is present'
require_pattern tools/build_signed_apps.sh 'Secure application is independent of DWT/CoreDebug and supports autonomous CLOSED boot' 'Signed Secure ELF rejects debug-domain timing dependencies'
require_pattern Secure/App/Src/safety_service.c 'SAFETY_STATUS_COMMAND_TIMEOUT' 'Secure actuator command timeout path is present'
require_pattern Secure/App/Src/safety_service.c 'SAFETY_ENGINE_START_MAX_MS' 'Secure engine starter hold limit is present'
require_pattern Secure/App/Src/safety_service.c 'GPIOE->BSRR = TPIC_CTRL_BUF_EN_Pin;' 'TPIC level shifter is enabled while OE remains fail-safe high'
require_pattern Secure/App/Src/safety_service.c 'if [(]!Safety_TpicShift[(]0U[)][)]' 'TPIC zero image is clocked and latched before outputs are armed'
require_pattern Secure/App/Src/safety_service.c '^#define ENGINE_TRIGGER_ACTIVE_MS[[:space:]]+1000UL$' 'K24/K25 engine-speed trigger is exactly one second'
require_pattern Secure/App/Src/safety_service.c 'mask &= ~[(]SAFETY_RELAY_ENGINE_SPEED_OVERRIDE' 'K3/K24/K25 are cleared before dynamic engine-speed selection'
reject_pattern Secure/App/Src/safety_service.c 'SAFETY_RELAY_VIB_REAR_OVERRIDE [|][[:space:]]*SAFETY_RELAY_ENGINE_SPEED_OVERRIDE' 'K3 is absent from the persistent normal-authority takeover mask'
require_pattern Secure/App/Src/safety_service.c 'engine_speed_state == ENGINE_SPEED_TRIGGER_ACTIVE' 'K24/K25 act only in the bounded trigger state'
require_pattern Secure/App/Src/safety_service.c 'ValveControl_Step' 'Secure ADC callback runs the valve current controller'
require_pattern Secure/App/Src/safety_service.c 'Safety_SaveValveConfig' 'Valve configuration persistence is owned by Secure code'
require_pattern Secure/App/Src/valve_control.c '^#define VALVE_OVERCURRENT_FAST_MA[[:space:]]+2500U$' 'Immutable fast overcurrent threshold is present'
require_pattern Secure/App/Src/valve_control.c 'SAFETY_STATUS_VALVE_OPEN_LOAD' 'Open-load protection is present'
require_pattern Secure/App/Src/valve_control.c 'VALVE_DIRECTION_DEADTIME_SAMPLES' 'Safe direction reversal deadtime is present'
require_pattern Secure/App/Src/valve_config_store.c '^#define VALVE_STORE_SECTOR_A[[:space:]]+125U$' 'Valve parameter journal starts in Secure sector 125'
require_pattern Secure/App/Src/valve_config_store.c '^#define VALVE_STORE_SECTOR_B[[:space:]]+126U$' 'Valve parameter journal alternates through Secure sector 126'
require_pattern Secure/App/Src/valve_config_store.c 'VALVE_STORE_COMMIT' 'Valve parameter records use a final commit marker'
require_pattern Secure_nsclib/safety_api.h 'K12; 1=run circuit' 'K12 physical run-permit semantics are explicit in the shared ABI'
require_pattern NonSecure/App/Src/ecu_app.c 'SECURE_SafetyKickWatchdog' 'NonSecure health heartbeat feeds Secure IWDG service'
require_pattern NonSecure/App/Src/ecu_network.c '#define CONTROL_TIMEOUT_MS[[:space:]]+250UL' 'UDP control authority expires after 250 ms'
require_pattern NonSecure/App/Src/ecu_network.c 'Network_TimeExpired[(]now, slot->last_update_tick, CONTROL_TIMEOUT_MS[)]' 'UDP timeout comparison is wrap-safe and cannot expire a callback timestamp from the next tick'
require_pattern NonSecure/App/Src/ecu_network.c 'slot->sequence_valid = false;' 'Expired UDP authority starts a recoverable new sequence session'
require_pattern NonSecure/App/Src/ecu_network.c '#define CONTROL_PRIORITY_EMERGENCY[[:space:]]+255U' 'Emergency network priority is fixed at 255'
require_pattern NonSecure/App/Src/ecu_network.c '#define CONTROL_MAX_SENDERS[[:space:]]+6U' 'Six-sender control capacity is retained in V2'
require_pattern NonSecure/App/Src/ecu_network.c 'datagram[.]control[.]emergency_stop_request != 0U' 'V2 emergency request is promoted to fail-safe emergency authority'
require_pattern NonSecure/App/Src/ecu_data_model.c 'run_permit_on = [(]control->emergency_stop_request == 0U[)]' 'Network E-stop semantic is inverted at the physical K12 boundary'
require_pattern NonSecure/App/Src/ecu_network.c 'udp_bind[(]transmit_pcb, IP_ANY_TYPE, ECU_STATUS_PORT[)]' 'Status source port remains UDP/50001'
require_pattern NonSecure/App/Src/ecu_network.c 'ECU_MESSAGE_VALVE_CONFIG_APPLY' 'V2 live valve tuning service is present'
require_pattern NonSecure/App/Src/ecu_network.c 'ECU_MESSAGE_VALVE_TELEMETRY' 'V2 valve telemetry service is present'
reject_pattern NonSecure/App 'throttle_percent' 'Obsolete percentage valve control is absent from active NonSecure code'
reject_pattern Secure/App 'throttle_percent' 'Obsolete percentage valve control is absent from Secure code'
require_pattern NonSecure/App/Network/lwipopts.h '^#define MEM_ALIGNMENT[[:space:]]+32$' 'Ethernet zero-copy pools preserve 32-byte buffer alignment'
require_pattern NonSecure/CMakeLists.txt 'eth_dma_sram3_guard[.]ld' 'NonSecure link includes the ETH DMA SRAM3 window guard'
require_pattern NonSecure/App/Linker/eth_dma_sram3_guard.ld 'ASSERT[(]__bss_end__ <= 0x20060000' 'LwIP/static data cannot outgrow the 64 KiB ETH DMA window'
require_pattern NonSecure/App/Inc/ecu_network.h '#define ECU_IP_ADDRESS_3[[:space:]]+11U' 'ECU static address is 172.16.0.11'
require_pattern NonSecure/App/Src/j1939.c 'HAL_FDCAN_ConfigGlobalFilter.*FDCAN_REJECT' 'CAN1 global filter rejects unspecified traffic'
require_pattern NonSecure/App/Inc/speed_sensor.h 'SPEED_SENSOR_PULSES_PER_KILOMETER 20000UL' 'Legacy speed calibration is retained'
require_pattern NonSecure/App/Src/ecu_protocol.c '_Static_assert[(]sizeof[(]ECU_StatusPayloadV2[)] == 100U' 'V2 UDP status ABI has a compile-time size guard'
require_pattern NonSecure/App/Inc/ecu_protocol.h '^#define ECU_V2_MAGIC[[:space:]]+0x32554345UL' 'V2 protocol magic is explicit'
require_file ThirdParty/LwIP/src/core/init.c 'Pinned LwIP sources are vendored outside generated directories'
require_file Drivers/BSP/Components/lan8742/lan8742.c 'LAN8742 PHY driver is vendored'
require_file tools/ecu_debug_ui/index.html 'Zero-dependency ECU acceptance UI is present'
require_file tools/configure_ecu_network.sh 'Idempotent enp2s0 bench-network helper is present'
reject_pattern tools/configure_ecu_network.sh '[|][[:space:]]*rg[[:space:]]' 'sudo network helper has no user-PATH ripgrep dependency'
require_file tools/check_ecu_latency.sh 'Ethernet latency regression gate is present'
require_pattern NonSecure/App/Network/ethernetif.c 'HAL_ETH_Transmit_IT' 'Ethernet transmit path is non-blocking'
reject_pattern NonSecure/App/Network/ethernetif.c 'HAL_ETH_Transmit[(]' 'Blocking Ethernet transmit is absent'
require_pattern NonSecure/Core/Src/eth.c '#define ECU_PHY_POWER_STABLE_MS[[:space:]]+30U' 'LAN8742A reset remains asserted beyond the 25 ms power-on minimum'
require_pattern NonSecure/Core/Src/eth.c 'HAL_Delay[(]ECU_PHY_POWER_STABLE_MS[)]' 'PHY power-on reset delay is in the CubeMX-preserved ETH_Init 0 block'
require_pattern NonSecure/Core/Src/eth.c 'HAL_GPIO_WritePin[(]RMII_NRST_GPIO_Port, RMII_NRST_Pin, GPIO_PIN_SET[)]' 'PHY reset is released before HAL ETH initialization'
reject_pattern NonSecure/App/Src/ecu_app.c 'HAL_GPIO_WritePin[(]RMII_NRST_GPIO_Port' 'Application cannot release the PHY after HAL ETH initialization'
require_pattern NonSecure/App/Network/ethernet_phy_policy.h '#define ECU_ETH_PHY_ADDRESS[[:space:]]+0U' 'LAN8742A probe is bound to the PCB PHYAD0 strap'
require_pattern NonSecure/App/Network/ethernet_phy_policy.h '#define ECU_ETH_PHY_ID1_EXPECTED[[:space:]]+0x0007U' 'LAN8742A OUI identity is explicit'
require_pattern NonSecure/App/Network/ethernetif.c '[*]value & 0xFFFFU.*== 0xFFFFU' 'Open MDIO reads cannot masquerade as a valid runtime PHY state'
require_pattern NonSecure/App/Network/ethernetif.c 'PHY discovery is recoverable' 'Transient PHY discovery failure does not stop the safety application'
require_file tests/test_ethernet_phy_policy.c 'PHY identity policy rejects open-bus all-ones reads'
require_file Secure/App/Src/security_ota_policy.c 'Paired MCUboot image_ok policy is isolated for exhaustive testing'
require_file tests/test_security_ota_policy.c 'All paired image_ok byte states are exhaustively tested'
require_pattern Secure/App/Src/security_ota.c 'SecurityOta_RunningImagesConfirmed' 'Secure startup validates both running MCUboot image_ok flags'
require_pattern Secure_nsclib/safety_api.h 'SAFETY_STATUS_OTA_UNCONFIRMED[[:space:]]*=[[:space:]]*[(]1UL << 25[)]' 'Existing status ABI carries a positive unconfirmed-image indication'
reject_pattern Secure/Core/Src/secure_nsc.c 'SECURE_SafetyOtaRunningImagesConfirmed' 'No new NSC query veneer can shift the installed v1 ABI'
reject_pattern Secure_nsclib/secure_nsc.h 'SECURE_SafetyOtaRunningImagesConfirmed' 'NonSecure uses the frozen GetStatus veneer for OTA state'
require_file Secure_nsclib/secure_nsc_abi_v1.s 'Firmware 1.0.12 NSC veneer map is versioned in source control'
require_pattern Secure/CMakeLists.txt '--in-implib=[^ ]*ECU_NSC_ABI_BASELINE_OBJECT' 'OEMiROT Secure link freezes existing NSC veneer addresses'
require_pattern Secure/CMakeLists.txt 'CMAKE_CURRENT_BINARY_DIR}/secure_nsclib[.]o' 'OEMiROT Secure import library is private to its build configuration'
require_pattern NonSecure/CMakeLists.txt 'ECU_OEMIROT_NSC_IMPORT' 'OEMiROT NonSecure links the matching private Secure import library'
reject_pattern NonSecure/CMakeLists.txt 'target_link_libraries[(][^)]*PRIVATE[^)]*ECU_OEMIROT_NSC_IMPORT' 'Private NSC import preserves CubeMX plain CMake link signature'
require_file tools/check_nsc_abi.py 'Signed-build NSC ABI binary checker is present'
require_pattern tools/build_signed_apps.sh 'check_nsc_abi[.]py' 'Every signed application build validates source, import, and SG veneer addresses'
require_pattern tools/build_signed_apps.sh '--nonsecure-elf' 'Signed-build ABI check validates the addresses resolved by the final NonSecure ELF'
require_file Bootloader/OEMiROT/Config/roller_pair_policy.h 'Paired-release loader policy is isolated and host-testable'
require_file tests/test_roller_pair_policy.c 'Paired swap, confirmation, and full release identity are unit tested'
require_pattern tools/test.sh 'test_roller_pair_policy[.]c' 'Paired loader policy test is part of the standard test suite'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Permanent swap is forbidden for paired releases' 'Paired product rejects independent PERM swaps'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Interrupted permanent swap is forbidden' 'Paired product rejects PERM before partial-swap recovery writes'
require_pattern tools/build_oemirot.sh 'partial_perm_guard < partial_review < partial_complete' 'Every OEMiROT build proves the partial PERM guard precedes recovery review and writes'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Conflicting paired TEST/REVERT state' 'Paired product rejects contradictory swap direction'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Unconfirmed primary cannot consume failed staging' 'Failed rollback staging cannot make OEMiROT synthesize application confirmation'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'fih_int roller_primary_pair_preconfirmed = FIH_FAILURE' 'Failed-staging authorization defaults to an encoded FIH failure'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'roller_primary_pair_preconfirmed = FIH_SUCCESS' 'Only the fully verified pre-confirmed pair opens the encoded FAIL recovery authorization'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'fih_not_eq\(roller_primary_pair_preconfirmed, FIH_SUCCESS\)' 'Failed-staging cleanup checks encoded authorization fail-closed'
require_pattern tools/build_oemirot.sh 'fail_fih_gate < fail_guard < fail_image_ok' 'Every OEMiROT build proves the unconfirmed FAIL guard precedes image_ok writes'
require_pattern tools/build_oemirot.sh 'fail_case < fail_fih_gate < fail_guard' 'Every OEMiROT build proves the encoded FAIL authorization gate is active before cleanup'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'bootutil_get_img_security_cnt' 'Paired release identity includes the signed protected security counter'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'roller_target_slot' 'Post-dependency target-pair validation covers resumed swaps'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Final paired primary release identities do not match' 'A final post-validation gate prevents any mixed primary pair from booting'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Paired image_ok read failed' 'First anti-rollback gate handles trailer read failures explicitly'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Paired countermeasure image_ok read failed' 'Countermeasure anti-rollback gate handles trailer read failures explicitly'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'RollerPair_AllImagesConfirmed' 'Both hardware counter paths require exact paired confirmation'
require_pattern tools/build_oemirot.sh 'paired loader safety gates are in the wrong order' 'Every OEMiROT build validates dependency/target/final/countermeasure gate ordering'
require_file tests/test_package_firmware.py 'Release identity history has fail-closed unit tests'
require_pattern tools/package_firmware.py 'validate_release_identity' 'Packaging rejects reuse of released versions and security counters'
require_pattern tools/package_firmware.py '--force may' 'Packaging documents that force cannot bypass release identity history'
require_pattern tools/package_firmware.py '^    if historical_versions and requested_version_tuple <= max[(]historical_versions[)]:$' 'Release version must independently exceed the complete historical maximum'
require_pattern tools/package_firmware.py '^    if historical_counters and requested_security_counter <= max[(]historical_counters[)]:$' 'Security counter must independently exceed the complete historical maximum'
require_pattern tools/package_firmware.py '^    if historical_sequences and requested_update_sequence <= max[(]historical_sequences[)]:$' 'OTA update sequence must independently exceed the complete historical maximum'
require_pattern_order tools/package_firmware.py '^        validate_release_identity[(]$' '^    run[(]\[str[(]PROJECT / "tools/build_signed_apps[.]sh"[)]' 'Release identity history is validated before any firmware build or signing action'
require_pattern tests/test_package_firmware.py 'test_existing_or_lower_version_is_rejected_even_with_newer_counters' 'Release-version monotonicity has an independent fail-closed test'
require_pattern tests/test_package_firmware.py 'test_existing_or_lower_security_counter_is_rejected_for_new_version' 'Security-counter monotonicity has an independent fail-closed test'
require_pattern tests/test_package_firmware.py 'test_existing_or_lower_update_sequence_is_rejected' 'OTA-sequence monotonicity has an independent fail-closed test'
require_pattern tests/test_package_firmware.py 'test_force_cannot_bypass_identity_gate_or_start_build' 'Force cannot bypass release history or start a build'
require_pattern Secure/App/Src/security_ota.c 'Acquire both Flash controllers before programming either flag' 'Both Flash domains unlock before the first image_ok write'
require_pattern Secure/App/Src/security_ota.c 'Confirm NonSecure first' 'Paired confirmation uses the reviewed power-loss recovery order'
require_file Secure/App/Src/secure_flash_guard.c 'Flash controller re-lock failures have a shared fail-safe guard'
require_pattern Secure/App/Src/secure_flash_guard.c 'NVIC_SystemReset[(][)]' 'A Flash re-lock failure resets into the hardware-locked state'
require_pattern Secure/App/Src/security_ota.c 'SecureFlash_LockSecureOrReset[(][)]' 'Secure OTA always re-locks Secure Flash or resets'
require_pattern Secure/App/Src/security_ota.c 'SecureFlash_LockNonSecureOrReset[(][)]' 'Paired confirmation always re-locks NonSecure Flash or resets'
require_pattern NonSecure/App/Src/ecu_app.c '#define ECU_OTA_CONFIRM_STARTUP_TIMEOUT_MS[[:space:]]+5000U' 'Unconfirmed OTA images have a bounded PHY startup deadline'
require_pattern NonSecure/App/Src/ecu_app.c 'ECU_NetworkStartupReady[(][)]' 'OTA image_ok requires a validated LAN8742 startup path'
require_pattern NonSecure/App/Src/ecu_app.c 'Already-confirmed images never enter this path' 'A permanent PHY fault cannot reboot a previously confirmed application'
require_pattern NonSecure/App/Src/ecu_app.c 'if [(]ota_confirmation_failed != 0U[)]' 'Failed confirmation stops application processing before watchdog service'
require_pattern NonSecure/App/Src/ecu_network.c 'if [(]network_operational == 0U[)]' 'Unconfirmed images keep control, tuning, and OTA traffic non-operational'
require_pattern Secure/App/Src/safety_service.c '^#define OTA_CONFIRM_WATCHDOG_GRACE_MS[[:space:]]+5000UL$' 'Secure watchdog independently bounds the test-image confirmation window'
require_pattern Secure/App/Src/safety_service.c 'Safety_TimeReached[(]secure_uptime_ms, ota_confirmation_deadline[)]' 'Secure confirmation refuses requests at or after its deadline'
require_pattern NonSecure/App/Src/ecu_network.c '^#define TELEMETRY_SEND_PERIOD_MS[[:space:]]+8UL$' '1 kHz samples are batched into bounded-rate telemetry frames'
require_file tools/program_ecu.sh 'Guarded TrustZone provisioning and flash helper is present'
require_pattern tools/program_ecu.sh 'check_target_identity' 'Flash helper verifies the reviewed target identity before writes'
require_pattern tools/program_ecu.sh 'backup_existing_flash' 'TrustZone provisioning backs up existing Flash before OB migration'
require_pattern tools/program_ecu.sh 'backup_persistent_storage' 'Normal firmware updates back up Secure identity, OTA journal, and valve parameter sectors'
require_pattern tools/program_ecu.sh 'verify_persistent_storage_unchanged' 'Normal firmware updates verify all Secure persistent data is preserved'
require_pattern tools/program_ecu.sh 'SECBOOTADD=0xC0000 SECBOOT_LOCK=0xC3' 'TrustZone provisioning persists the Secure boot address before reset'
require_file Bootloader/OEMiROT/Config/boot_hal_cfg.h 'Reviewed OEMiROT product-state policy is local to the project'
require_pattern Bootloader/OEMiROT/Config/boot_hal_cfg.h 'defined[(]ROLLER_OEMIROT_OPEN_BENCH[)]' 'OPEN bench compatibility is explicit and independent of debug behavior'
require_pattern Bootloader/OEMiROT/Config/boot_hal_cfg.h '^#define OEMIROT_OB_PRODUCT_STATE_VALUE OB_PROD_STATE_CLOSED$' 'Production OEMiROT profile requires the CLOSED product state'
require_pattern tools/build_oemirot.sh '^  ReleaseOpen[)]$' 'Optimized ReleaseOpen OEMiROT build profile is present'
require_pattern tools/build_oemirot.sh '^  ReleaseClosed[)]$' 'Optimized ReleaseClosed OEMiROT build profile is present'
require_pattern tools/build_oemirot.sh 'autonomous boot has no project call before SystemInit and no DWT/DBGMCU dependency' 'Both Release OEMiROT profiles enforce autonomous reset identity policy'
reject_pattern Bootloader/OEMiROT/CMakeLists.txt 'UID_BASE \+ [(]index' 'OEMiROT HDPL1 does not touch the unreliable engineering-information aperture'
reject_pattern Bootloader/OEMiROT/CMakeLists.txt 'DBGMCU->IDCODE|HAL_GetDEVID[(]|HAL_GetREVID[(]' 'OEMiROT source derivatives have no lifecycle-dependent DBGMCU path'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'idcode_a = ROLLER_RSS_IDCODE' 'All OEMiROT profiles use the reviewed RSS manifest'
require_pattern tools/build_oemirot.sh 'final ELF contains a debug/trace peripheral aperture' 'Both Release binary gates reject DBGMCU and DWT apertures'
require_pattern tools/build_oemirot.sh 'must not access DWT/CoreDebug' 'Both Release binary gates reject debug/trace-domain access'
require_pattern tools/build_oemirot.sh 'must not make a C call before ST reaches the post-ECC SystemInit boundary' 'Both Release binary gates reject project calls before ECC SRAM startup completes'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'Roller_ManufacturingManifestInit[(][)];' 'Manufacturing manifest initializes after the ST ECC SRAM startup sequence'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'removes debug-domain timing from every lifecycle profile' 'OEMiROT removes upstream debug timing from every lifecycle profile'
require_pattern Bootloader/OEMiROT/CMakeLists.txt 'handoff->mcu_uid\[0\] = ROLLER_DEVICE_UID0' 'Application handoff uses the reviewed per-device manufacturing identity'
reject_pattern Secure/Core/Src/main.c 'UID_BASE' 'OEMiROT Secure application does not expose the engineering-information aperture'
require_pattern Secure/App/Src/security_identity.c 'ATECC608_SignDigest' 'Startup pairing executes a live ATECC private-key challenge'
require_pattern Secure/App/Src/security_identity.c 'SecurityIdentity_McuUidMatches' 'Protected pairing record is bound to the reviewed MCU identity'
require_pattern Secure/App/Src/atecc608.c '^int32_t ATECC608_ProbeWithRecovery[(]$' 'Startup ATECC probe has an explicit host-reset recovery path'
require_pattern Secure/App/Src/atecc608.c '^#define ATECC608_STARTUP_RETRY_STEP_MS[[:space:]]+25U$' 'ATECC startup recovery includes the bounded POST delay step'
require_pattern Secure/App/Src/atecc608.c 'waited_ms >= ATECC608_STARTUP_RETRY_BUDGET_MS' 'ATECC startup retry has a hard maximum-execution-time budget'
require_pattern Secure/App/Src/safety_service.c 'ATECC608_ProbeWithRecovery' 'Secure startup uses the bounded ATECC recovery probe'
require_pattern Secure/App/Src/safety_service.c 'Safety_AteccRecoveryService' 'ATECC recovery services the already-running startup watchdog'
require_file tests/test_atecc608_recovery.c 'ATECC host-reset recovery has fail-closed state-model tests'
require_pattern tools/provision_oemirot_open.sh 'build/ReleaseOpen/ECU_OEMiROT[.]bin' 'OPEN provisioning cannot accidentally install the CLOSED boot profile'
require_pattern tools/provision_oemirot_open.sh '^task_persistent_size="0x20000"$' 'Provisioning backs up the complete canonical 128-KiB persistent partition'
require_pattern tools/provision_oemirot_open.sh '^check_blank_flash_sample[(][)]' 'Full Regression recovery requires an erased-Flash proof'
require_pattern tools/provision_oemirot_open.sh 'roller-ecu-full-regression-backup-v4' 'Full Regression recovery accepts only the current strict 1.0.15 backup manifest'
require_pattern tools/provision_oemirot_open.sh 'current recovery input is stale or unreviewed' 'Recovery refuses unreviewed OEMiROT or application binaries'
require_pattern tools/provision_oemirot_open.sh 'OBKs reproduced byte-for-byte from PKI/TPC inputs' 'Recovery proves OBKs are reproducible provisioning inputs, not DHUK exports'
require_pattern tools/provision_oemirot_open.sh 'recover-open-after-full-regression' 'Blank OPEN recovery is a separately gated provisioning action'
require_file tools/verify_open_loader_backup.py 'OPEN-only loader replacement validates a fresh paired-primary backup'
require_file tests/test_open_loader_backup.py 'OPEN-only loader backup validation has fail-closed unit tests'
require_pattern tools/verify_open_loader_backup.py 'Shared.*ecu_flash_layout[.]h' 'OPEN loader backup verifier consumes the canonical shared Flash geometry'
require_pattern tools/provision_oemirot_open.sh 'preflight-open-oemirot-replacement' 'OPEN loader replacement has a board-free offline preflight'
require_pattern tools/provision_oemirot_open.sh 'accept-open-boot-replacement' 'OPEN loader replacement requires explicit destructive acceptance'
require_pattern tools/provision_oemirot_open.sh 'mode=HWRSTPULSE' 'OPEN loader replacement proves physical NRST and JP1-low normal boot'
require_pattern tools/provision_oemirot_open.sh 'task_runtime_preflight_verifier[}]" runtime-state' 'OPEN loader replacement requires a fresh exact ATECC/runtime safety sample'
require_pattern tools/provision_oemirot_open.sh 'fresh_full_flash_persistent_ob_runtime_backup_complete' 'OPEN loader replacement captures a fresh complete recovery set before writes'
require_pattern tools/provision_oemirot_open.sh 'paired_primary_signature_identity_trailer_verified' 'OPEN loader replacement gates on paired signed and confirmed primaries'
require_pattern tools/provision_oemirot_open.sh 'programmer-mcu-uid-current[.]bin' 'OPEN loader resume rechecks the physical MCU UID through Programmer'
require_pattern tools/provision_oemirot_open.sh 'roller-ecu-1[.]0[.]14[.]recu' 'Mandatory OTA 1.0.14 bytes are pinned inside the replacement transaction'
require_pattern tools/provision_oemirot_open.sh 'from ethernet_ota import load_package' 'Mandatory OTA transaction validates the signed package before any target access'
require_pattern tools/provision_oemirot_open.sh 'sync -f .*task_open_loader_dir' 'OPEN loader recovery inputs reach stable storage before boot mutation'
require_pattern tools/provision_oemirot_open.sh 'require_size .*full-flash[.]bin.* 2097152' 'OPEN loader backup requires an exact 2-MiB full Flash capture'
require_pattern tools/provision_oemirot_open.sh 'require_size .*secure-persistent[.]bin.* 131072' 'OPEN loader backup requires the complete 128-KiB persistent partition'
require_pattern tools/provision_oemirot_open.sh 'ReleaseOpen-readback[.]bin' 'OPEN loader programming has an independent byte-for-byte readback'
require_pattern tools/provision_oemirot_open.sh 'resumed_boot_readback_reverified' 'Resume revalidates the staged boot bytes before restoring WRP/HDP'
require_pattern tools/provision_oemirot_open.sh 'replacement_complete_stlink_cold_start_embargo_active' 'Old application cold start is embargoed until OTA 1.0.14 confirmation'
require_pattern tools/provision_oemirot_open.sh 'transaction ReleaseOpen is not the reviewed exact artifact' 'OPEN loader resume independently re-pins the staged ReleaseOpen bytes'
require_pattern tools/provision_oemirot_open.sh 'transaction OTA package is not the reviewed exact 1[.]0[.]14 release' 'OPEN loader resume independently re-pins the staged OTA bytes'
require_file tools/create_full_regression_recovery.sh 'Versioned Full Regression recovery package generator is present'
require_pattern tools/create_full_regression_recovery.sh 'product_state_closed_verified' 'Recovery package creation requires a linked successful CLOSED transition'
require_pattern tools/create_full_regression_recovery.sh 'CLOSED_TRANSACTION_DIR' 'Recovery package creation consumes the exact immutable CLOSED transaction directory'
require_pattern tools/create_full_regression_recovery.sh 'roller-ecu-full-regression-backup-v4' 'Recovery package generator emits the strict v4 dual-pairing schema'
require_pattern tools/create_full_regression_recovery.sh '5fdaaa3f5e2d2a6c01ed527282ba08b3d8d5e579c61ec3c4e097cdf2c0fd7761' 'Recovery fixes the reviewed ReleaseOpen bytes'
require_pattern tools/create_full_regression_recovery.sh '9980acbf248f242c77c7044f48d627ca862d6714221f5835c0a21b7a24bf9e54' 'Recovery fixes the reviewed 1.0.15 signed OTA package'
require_file tests/test_full_regression_recovery.py 'Full Regression recovery package has end-to-end host tests'
require_pattern tools/provision_oemirot_open.sh 'validate-full-regression-package' 'Recovery package can be validated without target or private PKI access'
require_pattern tools/generate_security_provisioning.py '"obk_package_device_bound": False' 'Security manifest identifies generated OBKs as non-device-bound provisioning inputs'
require_pattern tools/generate_security_provisioning.py '^DA_FULL_REGRESSION = 1 << 14$' 'DA policy explicitly authorizes destructive Full Regression'
require_pattern tools/generate_security_provisioning.py '^DA_DEBUG_HDPL3_SECURE_NONSECURE = 1 << 6$' 'DA policy limits temporary application debug to HDPL3 S/NS'
reject_pattern tools/generate_security_provisioning.py 'DA_DEBUG_HDPL[12]' 'DA policy does not expose OEMiROT or HDPL2 debug'
require_file tools/ecu_debug_auth.py 'Gated field-service Debug Authentication tool is present'
require_pattern tools/ecu_debug_auth.py 'accept-full-device-erase' 'Full Regression requires explicit full-device erase acceptance'
require_pattern tools/ecu_debug_auth.py 'accept-closed-target' 'RSS-DA actions require explicit CLOSED-target acceptance'
require_pattern tools/ecu_debug_auth.py '"full-regression-to-open"[)] and not args[.]accept_closed_target:$' 'Full Regression independently requires exact CLOSED-target acceptance'
require_pattern tools/ecu_debug_auth.py 'not args[.]accept_full_device_erase:$' 'Full Regression independently requires destructive full-device-erase acceptance'
require_pattern tools/ecu_debug_auth.py 'Fully remove ECU power for at least 10 seconds' 'DA close requires a documented cold power cycle before return to service'
require_pattern tools/ecu_debug_auth.py '^        permission = "c" if args[.]action == "open-app-debug" else "a"$' 'DA maps app debug only to permission c and destructive Full Regression to permission a'
reject_pattern tools/ecu_debug_auth.py 'permission = "g" if args[.]action == "open-app-debug"' 'HDPL2 nonsecure permission g is not requested by the service tool'
require_file tests/test_ecu_debug_auth.py 'Debug Authentication acceptance and permission policy has host tests'
require_pattern tests/test_ecu_debug_auth.py 'test_closed_acceptance_is_required_before_any_programmer_access' 'CLOSED-target acceptance is tested before any Programmer access'
require_pattern tests/test_ecu_debug_auth.py 'test_full_regression_requires_erase_acceptance_independently' 'Full-device erase acceptance is tested independently'
require_pattern tests/test_ecu_debug_auth.py 'test_open_preflights_closed_then_uses_permission_c_and_success' 'Temporary application debug permission c is tested'
require_pattern tests/test_ecu_debug_auth.py 'test_full_regression_preflights_closed_and_uses_permission_a' 'Destructive Full Regression permission a is tested'
require_file tools/finalize_oemirot_closed.sh 'Gated OPEN-to-CLOSED manufacturing transition tool is present'
require_pattern tools/finalize_oemirot_closed.sh 'accept-irreversible-closed' 'CLOSED transition requires explicit irreversible-action acceptance'
require_pattern tools/finalize_oemirot_closed.sh 'mode=HWRSTPULSE' 'CLOSED preflight verifies that ST-Link NRST reaches the MCU'
require_file tools/verify_closed_preflight.py 'CLOSED identity/runtime/OTA/transaction verifier is present'
require_file tests/test_closed_preflight.py 'CLOSED fail-closed validators have host unit tests'
require_file tests/test_closed_finalizer.py 'CLOSED shell transaction has static host gates'
require_pattern tools/ecu_debug_ui.py 'security_age_ms' 'CLOSED gate can prove the ATECC security sample is fresh'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_MCU_UID = "003800613434511232383537"$' 'CLOSED gate pins the reviewed physical MCU UID'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_ATECC_SERIAL = "0123d47eb2ee0e9bee"$' 'CLOSED gate pins the reviewed ATECC serial'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_ATECC_CONFIG_CRC32C = 0xEBB326F3$' 'CLOSED gate pins the reviewed ATECC Config CRC-32C'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_PAIRING_GENERATION = 1$' 'CLOSED gate pins the reviewed ATECC pairing generation'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_ACCEPTED_SEQUENCE = 15$' 'CLOSED gate pins the accepted OTA sequence'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_RELEASE_CLOSED_SIZE = 52292$' 'CLOSED gate pins the reviewed ReleaseClosed loader size'
require_pattern tools/verify_closed_preflight.py '4073a9faa15eed7ca6014f168ae91efc35ba1e26d8e74651552c9a0a3d8ef884' 'CLOSED gate pins the reviewed ReleaseClosed loader hash'
require_pattern tools/verify_closed_preflight.py 'SAFETY_STATUS_OTA_UNCONFIRMED' 'Fresh runtime state must positively prove paired confirmation'
require_pattern tools/verify_closed_preflight.py '^EXPECTED_RELEASE_IDENTITY = \{' 'Fresh Flash backup is locked to exact release 1.0.15/counter 15 identity fields'
require_pattern tools/verify_closed_preflight.py '^    "revision": 15,$' 'CLOSED release identity pins firmware revision 15'
require_pattern tools/verify_closed_preflight.py '^    "security_counter": 15,$' 'CLOSED release identity pins anti-rollback counter 15'
require_file tools/verify_closed_ota_readback.py 'Exact post-CLOSED-OTA 1.0.16 primary readback verifier is present'
require_file tests/test_closed_ota_readback.py 'Exact post-CLOSED-OTA primary readback verifier has fail-closed tests'
require_pattern tools/verify_closed_ota_readback.py '^EXPECTED_VERSION = "1[.]0[.]16"$' 'Post-OTA verifier pins release 1.0.16'
require_pattern tools/verify_closed_ota_readback.py '^EXPECTED_IDENTITY = [(]1, 0, 16, 0, 16[)]$' 'Post-OTA verifier pins version and security counter 16'
require_pattern tools/verify_closed_ota_readback.py '^EXPECTED_UPDATE_SEQUENCE = 16$' 'Post-OTA verifier pins update sequence 16'
require_pattern tools/verify_closed_ota_readback.py '^SECURE_ADDRESS = FLASH_BASE_S [+] SECURE_OFFSET$' 'Secure readback address derives from the canonical Flash layout'
require_pattern tools/verify_closed_ota_readback.py '^NONSECURE_ADDRESS = FLASH_BASE_NS [+] NONSECURE_OFFSET$' 'NonSecure readback address derives from the canonical Flash layout'
require_pattern tools/verify_closed_ota_readback.py '"--secure-segment", action="append", required=True' 'Secure primary input requires explicitly addressed segments'
require_pattern tools/verify_closed_ota_readback.py '"--nonsecure-segment", action="append", required=True' 'NonSecure primary input requires explicitly addressed segments'
require_pattern tools/verify_closed_ota_readback.py 'address == cursor' 'Readback segment assembly rejects gaps, overlap, and out-of-order data'
require_pattern tools/verify_closed_ota_readback.py '^PINNED_PREVIOUS_RELEASE_ARTIFACT = [(]$' 'Post-swap audit has an immutable previous-release reference'
require_pattern tools/verify_closed_ota_readback.py '9980acbf248f242c77c7044f48d627ca862d6714221f5835c0a21b7a24bf9e54' 'Post-swap audit pins the exact 1.0.15 OTA artifact'
require_pattern tools/verify_closed_ota_readback.py '^PINNED_RELEASE_ARTIFACTS = \{$' 'Post-swap audit has an exact current-release artifact set'
require_pattern tools/verify_closed_ota_readback.py '3e5ab07c7b6127dcedb46a1b4b1a695740904dd940d7128631f714d959a0b623' 'Post-swap audit pins the exact 1.0.16 OTA artifact'
require_pattern tools/verify_closed_ota_readback.py 'set[(]entries[)] == set[(]PINNED_RELEASE_ARTIFACTS[)]' 'Post-swap audit rejects missing or extra 1.0.16 release artifacts'
require_pattern tools/verify_closed_ota_readback.py '^    swap_size = max[(]previous_record_size, update_record[.]record_end[)]$' 'Post-swap expected swap_size is max(previous,current) signed record size'
require_pattern tools/verify_closed_ota_readback.py 'struct[.]pack[(]"<I", swap_size[)] [+] b"\\xff" [*] 12' 'Installed swap_size is compared byte-for-byte with max(previous,current)'
require_pattern tests/test_closed_ota_readback.py 'test_geometry_and_release_are_exact_1_0_16' '1.0.16 identity and addressed primary geometry are unit tested'
require_pattern tests/test_closed_ota_readback.py 'test_accepts_exact_post_swap_pair_and_three_nonsecure_segments' 'Secure and segmented NonSecure addressed readbacks are unit tested'
require_pattern tests/test_closed_ota_readback.py 'test_release_rejects_missing_or_modified_previous_swap_reference' 'Pinned 1.0.15 swap reference is fail-closed tested'
require_pattern tests/test_closed_ota_readback.py 'test_nonsecure_swap_size_rejects_current_record_end_and_any_other_size' 'max(previous,current) swap_size enforcement is fail-closed tested'
require_pattern tools/finalize_oemirot_closed.sh '-u 0x08FFF800 0xC' 'Programmer reads the physical UID before CLOSED'
require_pattern tools/finalize_oemirot_closed.sh 'verify_open_loader_backup[.]py' 'CLOSED transaction audits both fresh primary slots and exact image_ok values'
require_pattern tools/finalize_oemirot_closed.sh 'installed-exact-1[.]0[.]15' 'CLOSED audit explicitly requires the exact reviewed post-swap 1.0.15 format'
require_pattern tools/verify_open_loader_backup.py 'encrypted primary cannot be audited' 'Pre-loader primary audit still rejects encrypted-header images by default'
require_pattern tools/verify_open_loader_backup.py 'PINNED_RELEASE_ARTIFACTS' 'Post-swap audit is bound to immutable reviewed release artifacts'
require_file tools/verify_pairing_store.py 'CLOSED manufacturing has an exact pairing-store verifier'
require_file tests/test_pairing_store.py 'Dual pairing-store validation has fail-closed host tests'
require_pattern tools/verify_pairing_store.py '^def verify_dual_store[(]' 'Pairing-store verifier validates both redundant sectors'
require_pattern tools/verify_pairing_store.py 'sector_a == sector_b' 'Pairing-store verifier requires byte-identical committed A/B copies'
require_pattern tools/finalize_oemirot_closed.sh 'verify_pairing_store[.]py' 'CLOSED transaction invokes the reviewed pairing-store verifier'
require_pattern tools/finalize_oemirot_closed.sh 'require_size .*pairing-store[.]bin.* 16384' 'CLOSED evidence requires the exact two-sector pairing-store size'
require_pattern tools/finalize_oemirot_closed.sh 'python3 "[$][{]task_pairing_verifier[}]" dual' 'CLOSED transition runs the verifier in dual-sector mode'
require_pattern tools/finalize_oemirot_closed.sh 'record_phase pairing_store_dual_verified' 'CLOSED transition durably records the dual pairing-store gate'
require_pattern tools/verify_closed_preflight.py '^    "pairing_store_dual_verified",$' 'CLOSED phase journal orders pairing validation before mutation evidence'
require_pattern tests/test_closed_preflight.py 'MODULE[.]CLOSED_PHASES\[:3\]' 'CLOSED phase-order test locks pairing validation between transaction creation and mutation evidence'
require_pattern tools/finalize_oemirot_closed.sh 'oemirot-auth-s-public[.]pem' 'CLOSED transaction verifies the Secure primary with the staged OEMiROT key'
require_pattern tools/finalize_oemirot_closed.sh 'oemirot-auth-ns-public[.]pem' 'CLOSED transaction verifies the NonSecure primary with the staged OEMiROT key'
require_pattern tools/finalize_oemirot_closed.sh 'sync -f "[$][{]task_transaction_dir[}]"' 'All CLOSED transaction inputs reach stable storage before mutation'
require_pattern tools/finalize_oemirot_closed.sh 'resume-closed-transition --accept-same-physical-target' 'CLOSED interruption recovery binds an explicit exact physical transaction'
require_pattern tools/finalize_oemirot_closed.sh 'flock -n 9' 'Concurrent CLOSED writers are rejected'
require_pattern tools/finalize_oemirot_closed.sh 'STM32CubeProgrammer exactly 2[.]23[.]0' 'CLOSED transaction pins the reviewed Programmer version'
require_pattern tools/finalize_oemirot_closed.sh 'stm32_programmer_sha256' 'CLOSED transaction pins the Programmer binary hash'
require_pattern tools/finalize_oemirot_closed.sh 'AMBIGUOUS SDP' 'An uncommitted OBKey result stops fail-closed'
require_pattern tools/finalize_oemirot_closed.sh 'ST_LIFECYCLE_PROVISIONING' 'CLOSED request requires pre-close DA provisioning lifecycle evidence'
require_pattern tools/finalize_oemirot_closed.sh 'ST provisioning integrity status' 'CLOSED request requires explicit pre-close DA integrity evidence'
require_pattern tools/finalize_oemirot_closed.sh 'PRODUCT_STATE=0x17' 'CLOSED resume classifies actual PROVISIONING before OBKey work'
require_pattern tools/finalize_oemirot_closed.sh 'record_phase closed_request_started' 'CLOSED lifecycle request uses a durable write-ahead phase'
require_pattern tools/finalize_oemirot_closed.sh 'IWDG_SW.*0x1' 'CLOSED gate preserves the ES0565 Debug Authentication IWDG requirement'
require_pattern tools/finalize_oemirot_closed.sh 'WRPSGn2.*0xFFFFFFFF' 'CLOSED gate verifies Bank 2 WRP remains in the reviewed state'
require_pattern tools/finalize_oemirot_closed.sh 'HDP2_STRT.*0x1' 'CLOSED gate verifies Bank 2 HDP start remains disabled'
require_pattern tools/finalize_oemirot_closed.sh 'HDP2_END.*0x0' 'CLOSED gate verifies Bank 2 HDP end remains disabled'
require_pattern tools/finalize_oemirot_closed.sh 'option-bytes-pre-provisioning[.]txt' 'CLOSED gate unconditionally rechecks all OPEN option bytes before provisioning'
require_pattern tools/finalize_oemirot_closed.sh 'os[.]replace[(]temporary_name, path[)]' 'CLOSED phase journal commits atomically'
require_pattern tools/finalize_oemirot_closed.sh 'preclose-da-attempt-' 'Every CLOSED write preserves a fresh actual-target DA discovery attempt'
require_pattern tools/finalize_oemirot_closed.sh 'verify_staged_against_reviewed_inputs' 'Every CLOSED fresh/resume path rebinds staged OBKeys and certificates to the reproduced PKI set'
require_pattern tools/verify_closed_preflight.py 'transaction file is missing or a symbolic link' 'CLOSED transaction inputs cannot redirect through symbolic links'
reject_pattern tools/finalize_oemirot_closed.sh '-sdp "[$][{]task_assets' 'CLOSED mutation never reads a mutable global OBKey path'
reject_pattern tools/finalize_oemirot_closed.sh '-d "[$][{]task_boot_image[}]" 0x0C000000' 'CLOSED mutation never reads a mutable build output'
reject_pattern docs/ECU_Security_and_OTA.md '双采样实时 DBGMCU|双采样实时 device' 'Security documentation does not claim nonexistent runtime DBGMCU identity sampling'
reject_pattern docs/ECU_Bench_Acceptance.md '双采样实时 DBGMCU|双采样实时 device' 'Acceptance record does not claim nonexistent runtime DBGMCU identity sampling'
require_pattern docs/ECU_Security_and_OTA.md 'HUK 封装的 OBKeys' 'Security documentation identifies the real MCU-bound boot root'
require_pattern docs/ECU_Security_and_OTA.md 'resume-closed-transition' 'Security documentation includes exact CLOSED transaction recovery'
require_pattern Secure/App/Src/security_ota.c '_Static_assert[(]OTA_BOOT_MAX_ALIGN == ECU_FLASH_PROGRAM_UNIT' 'OTA image confirmation alignment is compile-time guarded'
require_pattern Secure/App/Src/security_ota.c '_Static_assert[(]OTA_IMAGE_OK_OFFSET_FROM_END == 32U' 'OEMiROT image_ok trailer offset is compile-time guarded'
require_pattern Secure/App/Src/security_ota.c '^#define OTA_RECORD_SCHEMA_CURRENT[[:space:]]+2UL$' 'OTA replay journal uses the guarded schema-2 commit format'
require_pattern Secure/App/Src/security_ota.c 'record[.]commit_inverse = [(]uint32_t[)][(]~OTA_RECORD_COMMIT[)]' 'OTA journal final Flash word contains a non-sparse inverse guard'
require_pattern Secure/App/Src/security_ota.c 'record[.]generation_copy = record[.]generation' 'OTA journal atomically duplicates its generation in the commit word'
require_pattern Secure/App/Src/security_ota.c 'record[.]accepted_sequence_copy = record[.]accepted_sequence' 'OTA journal atomically duplicates its accepted sequence in the commit word'
require_pattern Secure/App/Src/security_ota.c 'HAL_ICACHE_Invalidate[(][)]' 'OTA invalidates cached Flash lines before write verification'
require_pattern Secure/App/Src/security_ota.c 'HAL_FLASH_Unlock_S[(][)]' 'Secure OTA storage uses the Secure-only Flash controller'
require_pattern Secure/App/Src/security_ota.c 'HAL_FLASH_Unlock_NS[(][)]' 'NonSecure image confirmation uses the NonSecure-only Flash controller'
reject_pattern Secure/App/Src/security_ota.c '^[[:space:]]*if .*HAL_FLASH_Unlock[(][)]' 'OTA code does not couple Secure and NonSecure Flash unlocks'
require_pattern Secure/App/Src/security_identity.c 'HAL_FLASH_Unlock_S[(][)]' 'Secure identity storage uses the Secure-only Flash controller'
require_pattern Secure/App/Src/security_identity.c 'HAL_ICACHE_Invalidate[(][)]' 'Secure identity records invalidate cached Flash lines before validation'
require_pattern Secure/App/Src/security_identity.c 'SECURITY_IDENTITY_ADDRESS_B, &record' 'Factory pairing persists and verifies the redundant B-sector record'
require_pattern Secure/App/Src/security_identity.c 'SecurityIdentity_RecordMatchesManifest[(]record_b, manifest[)]' 'Factory pairing finalizer verifies the committed B-sector identity'
require_pattern Secure/App/Src/valve_config_store.c 'HAL_FLASH_Unlock_S[(][)]' 'Secure valve calibration storage uses the Secure-only Flash controller'
require_pattern Secure/App/Src/valve_config_store.c 'HAL_ICACHE_Invalidate[(][)]' 'Valve calibration records invalidate cached Flash lines before validation'
reject_file Bootloader/OEMiROT/Src/boot_trace.c 'Temporary OEMiROT startup trace source is absent'
reject_file Secure/App/Src/security_boot_trace.c 'Temporary Secure startup trace source is absent'
reject_file NonSecure/App/Src/ecu_boot_trace.c 'Temporary NonSecure startup trace source is absent'
require_file tools/ecu_bench_test.py 'Guarded Ethernet actuator acceptance test is present'
require_pattern Secure/STM32H563xx_FLASH_s.ld 'ORIGIN = 0xc000000,    LENGTH = 1000K' 'Secure Flash excludes both valve parameter sectors and NSC'
require_pattern Secure/App/Linker/valve_config_flash_guard.ld '__data_source_end <= 0x0C0E0000' 'Additional linker guard protects all Secure persistent sectors after CubeMX regeneration'
require_pattern Secure/STM32H563xx_FLASH_s.ld 'ORIGIN = 0xc0fe000,    LENGTH = 8K' 'NSC linker region is the last Bank1 sector'
require_pattern NonSecure/STM32H563xx_FLASH_ns.ld 'ORIGIN = 0x8100000,    LENGTH = 1024K' 'NonSecure Flash linker region matches Bank2'

if ((task_failures != 0)); then
  printf '\nConfiguration audit failed: %d check(s).\n' "${task_failures}" >&2
  exit 1
fi

printf '\nConfiguration audit passed.\n'
