import pathlib
import struct
import sys
import unittest


PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

import ecu_legacy_v1 as legacy  # noqa: E402


# Generated by the previous firmware tree's unmodified ccu_protocol.py.
GOLDEN_SAFE_CONTROL = bytes.fromhex(
    "a50027020200007856341201000100000000010000000000010001010001fe"
    "0000000000000100000100f75a"
)


class LegacyV1ProtocolTests(unittest.TestCase):
    def test_frozen_sizes_and_golden_control_frame(self):
        self.assertEqual(legacy.CONTROL_DATAGRAM_SIZE, 39)
        self.assertEqual(legacy.STATUS_PAYLOAD_SIZE, 77)
        self.assertEqual(len(GOLDEN_SAFE_CONTROL), 44)
        decoded = legacy.decode_control_frame(GOLDEN_SAFE_CONTROL)
        self.assertEqual(decoded["sender_id"], 2)
        self.assertEqual(decoded["priority"], 2)
        self.assertEqual(decoded["flags"], 0)
        self.assertEqual(decoded["sequence"], 0x12345678)
        self.assertEqual(decoded["engine_speed_level"], -2)
        self.assertEqual(decoded["throttle_percent"], 0)
        control = {name: decoded[name] for name in legacy.CONTROL_FIELDS}
        rebuilt = legacy.build_safe_control_frame(
            control, sender_id=2, priority=2, sequence=0x12345678
        )
        self.assertEqual(rebuilt, GOLDEN_SAFE_CONTROL)

    def test_frame_integrity_is_strict(self):
        malformed = bytearray(GOLDEN_SAFE_CONTROL)
        malformed[3] ^= 1
        with self.assertRaisesRegex(ValueError, "parity"):
            legacy.decode_control_frame(bytes(malformed))
        malformed = bytearray(GOLDEN_SAFE_CONTROL)
        malformed[2] -= 1
        with self.assertRaisesRegex(ValueError, "length"):
            legacy.decode_control_frame(bytes(malformed))
        malformed = bytearray(GOLDEN_SAFE_CONTROL)
        malformed[-1] = 0
        with self.assertRaisesRegex(ValueError, "delimiter"):
            legacy.decode_control_frame(bytes(malformed))
        with self.assertRaisesRegex(ValueError, "size"):
            legacy.decode_control_frame(GOLDEN_SAFE_CONTROL + b"\0")

    def test_motion_and_absent_outputs_are_rejected_not_translated(self):
        forbidden = (
            "steering_target_tdeg", "steering_speed_tdeg_per_s",
            "steering_enable", "throttle_percent", "indicator1_on",
            "indicator2_on", "indicator3_on", "power_latch_on",
            "main_power_relay_on",
        )
        for field in forbidden:
            with self.subTest(field=field):
                with self.assertRaisesRegex(ValueError, "unsupported"):
                    legacy.build_safe_control_frame(
                        {field: 1}, sender_id=1, priority=1, sequence=1
                    )
        with self.assertRaisesRegex(ValueError, "flags"):
            legacy.build_safe_control_frame(
                {}, sender_id=1, priority=1, sequence=1, flags=1
            )
        with self.assertRaisesRegex(ValueError, "exactly"):
            legacy.build_safe_control_frame(
                {"pump_enable": 2}, sender_id=1, priority=1, sequence=1
            )

    def test_raw_emergency_remains_decodable_before_semantic_validation(self):
        values = {name: 0 for name in legacy.CONTROL_FIELDS}
        values["emergency_stop_on"] = 1
        values["throttle_percent"] = 100
        payload = struct.pack(
            legacy.CONTROL_DATAGRAM_FORMAT, 3, 3, 0xFFFF, 7,
            *(values[name] for name in legacy.CONTROL_FIELDS),
        )
        decoded = legacy.decode_control_frame(legacy.encode_frame(payload))
        self.assertEqual(decoded["emergency_stop_on"], 1)
        self.assertEqual(decoded["throttle_percent"], 100)
        with self.assertRaises(ValueError):
            legacy.validate_safe_control(values, 0xFFFF)

    def test_status_sequence_timestamp_and_deprecated_throttle(self):
        values = {name: 0 for name in legacy.STATUS_FIELDS}
        values.update(
            sequence_id=0x01020304,
            timestamp_ms=0xA0B0C0D0,
            water_mv=1234,
            engine_speed_level=-3,
            throttle_percent=0,
            parking_brake_on=1,
            control_mode=3,
            active_sender_id=3,
            j1939_engine_rpm=16000,
        )
        payload = struct.pack(
            legacy.STATUS_PAYLOAD_FORMAT,
            *(values[name] for name in legacy.STATUS_FIELDS),
        )
        frame = legacy.encode_frame(payload)
        self.assertEqual(len(frame), 82)
        decoded = legacy.decode_status_frame(frame)
        self.assertEqual(decoded["sequence_id"], 0x01020304)
        self.assertEqual(decoded["timestamp_ms"], 0xA0B0C0D0)
        self.assertEqual(decoded["water_mv"], 1234)
        self.assertEqual(decoded["engine_speed_level"], -3)
        self.assertEqual(decoded["throttle_percent"], 0)
        self.assertEqual(decoded["active_sender_id"], 3)

    def test_percentage_control_is_confined_to_frozen_reject_adapter(self):
        matches = []
        for path in sorted((PROJECT_ROOT / "NonSecure" / "App").rglob("*")):
            if path.is_file():
                try:
                    lines = path.read_text(encoding="utf-8").splitlines()
                except UnicodeDecodeError:
                    continue
                for line in lines:
                    if "throttle_percent" in line:
                        matches.append((path.relative_to(PROJECT_ROOT), line.strip()))
        self.assertEqual(
            matches,
            [
                (pathlib.Path("NonSecure/App/Inc/ecu_protocol.h"),
                 "int8_t throttle_percent;"),
                (pathlib.Path("NonSecure/App/Inc/ecu_protocol.h"),
                 "int8_t throttle_percent;"),
                (pathlib.Path("NonSecure/App/Src/ecu_protocol.c"),
                 "(control->throttle_percent != 0) ||"),
                (pathlib.Path("NonSecure/App/Src/ecu_protocol.c"),
                 "destination->throttle_percent = 0;"),
            ],
        )

    def test_network_source_keeps_v1_emergency_before_semantic_reject(self):
        source = (PROJECT_ROOT / "NonSecure/App/Src/ecu_network.c").read_text()
        decode = source.index("ECU_ProtocolDecodeV1")
        emergency = source.index("legacy.control.emergency_stop_on", decode)
        conversion = source.index("ECU_ProtocolConvertControlV1", emergency)
        self.assertLess(decode, emergency)
        self.assertLess(emergency, conversion)
        self.assertIn("ECU_CAP_LEGACY_V1_SAFE_CONTROL", source)
        self.assertIn("LEGACY_STATUS_PERIOD_MS", source)
        self.assertIn("LEGACY_STATUS_PHASE_MS", source)
        self.assertNotIn("legacy_status_lease", source)

    def test_legacy_status_is_unconditional_and_phase_staggered(self):
        source = (PROJECT_ROOT / "NonSecure/App/Src/ecu_network.c").read_text()
        self.assertIn("#define LEGACY_STATUS_PERIOD_MS        50UL", source)
        self.assertIn("#define LEGACY_STATUS_PHASE_MS         25UL", source)
        self.assertRegex(
            source,
            r"(?s)\[ETHERNET_TX_CATEGORY_LEGACY\].*?"
            r"\.period_ms = LEGACY_STATUS_PERIOD_MS,.*?"
            r"\.phase_ms = LEGACY_STATUS_PHASE_MS",
        )
        self.assertIn("case ETHERNET_TX_CATEGORY_LEGACY:", source)
        self.assertIn("Network_SendLegacyStatus()", source)
        self.assertNotIn("last_legacy_status_tick", source)


if __name__ == "__main__":
    unittest.main()
